#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.
# Perl 脚本文件，用于生成用户级系统调用（user-level system call）的相关代码
#The Makefile invokes the perl script user/usys.pl, which produces user/usys.S, 
#the actual system call stubs, which use the RISC-V ecall instruction to transition to the kernel.
#Makefile文件调用了一个名为usys.pl的Perl脚本，并生成了usys.S文件，
#这个文件包含了实际的系统调用存根。这些存根使用RISC-V ecall指令将控制权转移到内核。
print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("trace");
entry("sysinfo");